version: '3.8'

services:
  eve-ui:
    image: eve-ui
    container_name: eve-ui
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION}
    ports:
      - "9191:9191"
    volumes:
      - ./env/env.prop:/app/env.prop
      - ./db/sqlite-latest.sqlite:/db/sqlite-latest.sqlite
    env_file:
      - env/env.prop
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
