services:
  eve-ui:
    image: eve-ui
    container_name: eve-ui
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: 1.4.0
    ports:
      - "9191:9191"
    volumes:
      - ./env/env.prop:/app/env.prop
      - ./db/sqlite-latest.sqlite:/db/sqlite-latest.sqlite
    env_file:
      - env/env.prop
    restart: unless-stopped
